# Generated by Django 4.0.6 on 2022-07-04 20:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('created', 'создан'), ('launched', 'запущен'), ('stopped', 'остановлен')], default='created', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
        ),
    ]
