# Generated by Django 4.0.6 on 2022-07-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_alter_object_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='date',
            new_name='time_of_creation',
        ),
    ]
