# Generated by Django 4.0.6 on 2022-07-05 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0003_rename_date_object_time_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='performers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Время создания'),
        ),
    ]
